language: go
sudo: false # see: https://docs.travis-ci.com/user/ci-environment/
addons:
  apt:
    packages:
      - rpm # fpm requirement for building rpms
go:
  - 1.7
env:
  global:
    - VERSION=0.1.1-dev
    # for coveralls.io
    - secure: e1Kpf604YM5lAM4x3R+yHYdupRawjscETI4UenGDjGMKmevyZEZa4Py8ih0mz6P64K0DW0iWEara9b09Oy+qEj36TB/RU3IZGcJ2GvMEOLZWzaXfYx4lhZ5Xq3KfPY2r9ikcPHIImukbMpmivW69rH7X14rUFWKyNooLM4NiPKAwUxIyM75GZDsuQ6FG0ejjepCp2sjNHzl8VWB0yXCbROFmrx74IQ8Yjlt1A2RTwTHR36WtyIQ7tAzWFNNZhXhapDRHLWLRV3vFfOyMXRlyhZYkwJP1IbtgUpiz+Nj/lmOYInEPy/stWfA2LHTQiS/uUXkSVgdm52IOesdD+IsJr4juXPE94WB0gTIlXqBVLnEeeF3/FAqLo80plv+YJie3/Xfukn9/AsoKCs47P8UyPSQq68qvd8dvnvmFtTqg+bH7DT8G7pv5Dpy1RDNJwf8XPmAgV/SkivFuTAUlPJSkkHGMh/JbjLdUAgc7MzJJFXY8aiw2mJGyfhli//CaLHY2N4bsCizw8xjqGOUHzVhEbDg0b2/2SEdCEqwZu0gmAGFwLLVtZWm22tm6uzPw6mTdMEHZmFSj4xtG5iZCVleka/LlQYETEY9Ch1gfm6TXVTHcDqUrj1wrcTi4kRnUPeUBP8ScQYHJ+gK2N9br4+MME+eHwir4Nhu6S5jTc/tVEno=
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go generate
  - go test -v -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
before_deploy:
  # chandler needs ruby version >= 2.2 => install it via rvm (reuse travis installed one)
  - ruby -v && rvm install 2.3.1 && rvm use --default 2.3.1 && ruby -v
  - ./travis/before_deploy.sh
  
deploy:
  - provider: releases
    api_key:
      secure: CmQG72+0QP+NKSMybCAwnR5pY0xYqMPfJgpSNPHW910IIkNsx39pZyGINDUXuwfoHwMkjCdloQpodfkLLjjc+gPhZ7Rt0cMb8NfOUQJeYWUme/yV+KTAk19nMzC/O78xNM1OnwqWCWwPmtH55pvTcqT3R3LjaSlHVveLQsJQa1rYbDxKaGlVPIfezR3HV0DsxRtwNCLOaNoRC3rIT2ILxPeovKhiUG3dbetboO1I1KbcyuDkNqWPLRggNy93NO9VvmkLMVm2Z5CMpkzRv+WLbhedVYfTzM05VOu2UMirh8aSjVSfRMlSHVAxDRXvtGP3hOJlV03LwMeV8zxJo+/nyPna/T7fXTM26w8MKB+uWJlXynHKE/W5t8XUB0BS1KAlum8ZnUhoTZ4YRU6rXAImlT8kJT6ouuVhe5z6ihIVpGjTdT3A7plqFBRQQVc0bp5G+t15VQY3nY39S/kBvjPf24wR6T7BCf939AAOxU7tEeRPk3YPeIikf5j8gfek+8GoN0Aaruzs1LqFisFvVs/yDAwF9gRXQ4FanrygqJH2t3PD5MgOjdBAdySie6lfZ9vGxZ7iESeEaL+feG80VZY2g+bTHcS2wiEL/PUToo4yL6/FbSIwAsEJCIQkFKPFw+EKa2b9/S86YFuF3/97HH/7+J0avFGihXr3yZrUopcPgMU=
    file_glob: true
    file:
      - "dist/*"    
    skip_cleanup: true
    on:
      repo: datarator/datarator
      tags: true

  - provider: bintray
    file: travis/bintray.json
    user: typekpb
    key:
      secure: YDGGhABiuiczVgI5knZ/u5VLVIBvBLfCTefoP196Lc2uzx7McFehCrk/n1XI6ilnk6abBQOhHP8cTcBQcWeEbgvJjAWAiE5OP04pBp001oMjOw1YrmhOtIUmgzcJtMAZOZaQGm4lhpRO5tDTufExRJ76b5ScmImXZqzj1elADEBxQID9+nmcfDDsa8roAmKLgD63mpwjortSRtMU2b8hxzYghhSjCtee4oyNvo64nrWaaqPm7OGVhukdYqkcZ5cSdLVj17M2lCSmuBLdd25uToS1jZq+VF114rRdsjSlVyysJOSdABR7Jx7xX5UQ6A5f12ic6XBwFnkRBbsl08RCRUuAr2V5Gjr4IPt9ibgs/pnHFPCQTw3UGPl0pqZli6b0dJcpWLR7gf6GGeyP0ReETqItdYPXJsk6MP4o3Jp1rIGBDwOsGTJllGN9sSFQQrpXRBOasPAIYMrStqqlA1fR974wQqXHQeqkImWH9U0eKAB/t3s7Y0XFES95sKU0f2X7v0Y7vVnAGYu8WThVUsh7IMR/67ia1LR4WmQBxYZVLQgS91D/qZyWjA9FpH2FnG7KQlPttDRU5mpujxWByOyLj+3IoSoy78goLb7PdPFi7s+AOUKe0nbyzYLIqxVz5VptXnkJFGzheIT1w7JjYxcqSmksNkwpgT5A6snAKEj+YDA=
    skip_cleanup: true
    on:
      repo: datarator/datarator
      tags: true

  # - provider: bintray
  #   file: travis/bintray_deb.json
  #   user: typekpb
  #   key:
  #     secure: YDGGhABiuiczVgI5knZ/u5VLVIBvBLfCTefoP196Lc2uzx7McFehCrk/n1XI6ilnk6abBQOhHP8cTcBQcWeEbgvJjAWAiE5OP04pBp001oMjOw1YrmhOtIUmgzcJtMAZOZaQGm4lhpRO5tDTufExRJ76b5ScmImXZqzj1elADEBxQID9+nmcfDDsa8roAmKLgD63mpwjortSRtMU2b8hxzYghhSjCtee4oyNvo64nrWaaqPm7OGVhukdYqkcZ5cSdLVj17M2lCSmuBLdd25uToS1jZq+VF114rRdsjSlVyysJOSdABR7Jx7xX5UQ6A5f12ic6XBwFnkRBbsl08RCRUuAr2V5Gjr4IPt9ibgs/pnHFPCQTw3UGPl0pqZli6b0dJcpWLR7gf6GGeyP0ReETqItdYPXJsk6MP4o3Jp1rIGBDwOsGTJllGN9sSFQQrpXRBOasPAIYMrStqqlA1fR974wQqXHQeqkImWH9U0eKAB/t3s7Y0XFES95sKU0f2X7v0Y7vVnAGYu8WThVUsh7IMR/67ia1LR4WmQBxYZVLQgS91D/qZyWjA9FpH2FnG7KQlPttDRU5mpujxWByOyLj+3IoSoy78goLb7PdPFi7s+AOUKe0nbyzYLIqxVz5VptXnkJFGzheIT1w7JjYxcqSmksNkwpgT5A6snAKEj+YDA=
  #   skip_cleanup: true
  #   on:
  #     repo: datarator/datarator
  #     tags: true

  # - provider: bintray
  #   file: travis/bintray_rpm.json
  #   user: typekpb
  #   key:
  #     secure: YDGGhABiuiczVgI5knZ/u5VLVIBvBLfCTefoP196Lc2uzx7McFehCrk/n1XI6ilnk6abBQOhHP8cTcBQcWeEbgvJjAWAiE5OP04pBp001oMjOw1YrmhOtIUmgzcJtMAZOZaQGm4lhpRO5tDTufExRJ76b5ScmImXZqzj1elADEBxQID9+nmcfDDsa8roAmKLgD63mpwjortSRtMU2b8hxzYghhSjCtee4oyNvo64nrWaaqPm7OGVhukdYqkcZ5cSdLVj17M2lCSmuBLdd25uToS1jZq+VF114rRdsjSlVyysJOSdABR7Jx7xX5UQ6A5f12ic6XBwFnkRBbsl08RCRUuAr2V5Gjr4IPt9ibgs/pnHFPCQTw3UGPl0pqZli6b0dJcpWLR7gf6GGeyP0ReETqItdYPXJsk6MP4o3Jp1rIGBDwOsGTJllGN9sSFQQrpXRBOasPAIYMrStqqlA1fR974wQqXHQeqkImWH9U0eKAB/t3s7Y0XFES95sKU0f2X7v0Y7vVnAGYu8WThVUsh7IMR/67ia1LR4WmQBxYZVLQgS91D/qZyWjA9FpH2FnG7KQlPttDRU5mpujxWByOyLj+3IoSoy78goLb7PdPFi7s+AOUKe0nbyzYLIqxVz5VptXnkJFGzheIT1w7JjYxcqSmksNkwpgT5A6snAKEj+YDA=
  #   skip_cleanup: true
  #   on:
  #     repo: datarator/datarator
  #     tags: true

  - provider: heroku
    api_key:
      secure: oZC94TkxGRF9ZxPKvFo5iSSqKwb5t3LFeLRbQ3xosYR7aP3lRBghkqqlFXorT3GM4+8p2jYwb61OZ2xAWjun98+E62gPWHYtc8v5tNoXJ9CgjV4i30z8mELfmllWFgmzJ0Hco/lJHbKMyuiaNUevlg7MfKBlU597HgABZ52IUWHt5pl9/3oX+zoeqy/Dcxs8O7vXJsghr31gYbwPS/OCp4203RV6uhrYin1EDbJoVZpXRVirO/KVjOJC4V4+jONwg0qwkrL9mLx3d6nLKnPqgWdt+2PPUn97qLzkK089Qa5UYEM5IkcgF73nP14UUYimaj6LbWp552JsyBkmkazml6fD8vkBbAu8THF4v1l1BqOw/WrjP4NCvxXv8fdwU3vHop0JvMFVo9hmP355AU3x2MriN5mJJCmHc5QGNNoqCJrpdKtW0OOftNiLEjYr/Gz76IUyxJ/3vCXXinl5/KIhuiZ4M7hTPwaPTL+ISawyWIGl1e+vKQzx8GPYXWSRbZMfO68DGLyN2OeEcYdtouKu9OOwVShMpMVJ2Dwx7FNlPX2pdC2Tk9UkzR2ysvpAF0BCd9vRNCPf0bFGV0Cc5eQtY7JZIU6SZpYkTJBHqnOHnL6e7s8OtMkaMrlPWoM1wAQoe1YJF8f3lQqV26M6nj3Q4J/hJhtvG1vrx30KB7ZzF6c=
    skip_cleanup: true
    on:
      repo: datarator/datarator
      tags: true