language: go
sudo: false # see: https://docs.travis-ci.com/user/ci-environment/
addons:
  apt:
    packages:
      - rpm # fpm requirement for building rpms
go:
  - 1.7
env:
  - VERSION=0.1.0 FPM_ARGS="-s dir -n datarator -v ${VERSION} --prefix '/usr/local/bin' --license MIT --vendor 'http://github.com/datarator/datarator' --rpm-summary 'Stateless data generator with HTTP based JSON API' --description 'Stateless data generator with HTTP based JSON API' -m 'Peter Butkovic <butkovic@gmail.com>'"
script:
  - go generate
  - go test -v ./...
before_deploy:
  # build cross-arch binaries
  - go get github.com/mitchellh/gox && gox -output='dist/{{.Dir}}_{{.OS}}_{{.Arch}}' -osarch="linux/amd64"
  # chandler needs ruby version >= 2.2 => install it via rvm (while reuse travis installed rvm)
#  - ruby -v && rvm install 2.3.1 && rvm use --default 2.3.1 && ruby -v
  # build platform specific packages
#  - gem install --no-ri --no-rdoc fpm && cp -f dist/datarator_linux_386 datarator && for target in deb rpm apk; do echo fpm -t ${target} "${FPM_ARGS}" -a 386 datarator | /bin/bash; done && cp -f dist/datarator_linux_amd64 datarator && for target in deb rpm apk; do echo fpm -t ${target} "${FPM_ARGS}
  - gem install --no-ri --no-rdoc fpm && cp -f dist/datarator_linux_386 datarator && for target in deb rpm; do echo fpm -t ${target} "${FPM_ARGS}" -a 386 datarator | /bin/bash; done && cp -f dist/datarator_linux_amd64 datarator && for target in deb rpm; do echo fpm -t ${target} "${FPM_ARGS}" -a amd64 datarator | /bin/bash; done
  # datarator file is beeing kept on purpose, as it is used for heroku deployment 
  # sync changelog with gh releases
  # disabled for now, see: https://travis-ci.org/datarator/datarator/builds/157375756
#  - gem install --no-ri --no-rdoc chandler && echo "machine api.github.com\n  login typekpb\n  password ${OAUTH_TOKEN}" >> ~/.netrc && chmod 600 ~/.netrc && cat ~/.netrc && chandler --changelog=$(pwd)/docs/CHANGELOG.md --github=datarator/datarator push

deploy:
  provider: releases
  api_key:
    secure: CmQG72+0QP+NKSMybCAwnR5pY0xYqMPfJgpSNPHW910IIkNsx39pZyGINDUXuwfoHwMkjCdloQpodfkLLjjc+gPhZ7Rt0cMb8NfOUQJeYWUme/yV+KTAk19nMzC/O78xNM1OnwqWCWwPmtH55pvTcqT3R3LjaSlHVveLQsJQa1rYbDxKaGlVPIfezR3HV0DsxRtwNCLOaNoRC3rIT2ILxPeovKhiUG3dbetboO1I1KbcyuDkNqWPLRggNy93NO9VvmkLMVm2Z5CMpkzRv+WLbhedVYfTzM05VOu2UMirh8aSjVSfRMlSHVAxDRXvtGP3hOJlV03LwMeV8zxJo+/nyPna/T7fXTM26w8MKB+uWJlXynHKE/W5t8XUB0BS1KAlum8ZnUhoTZ4YRU6rXAImlT8kJT6ouuVhe5z6ihIVpGjTdT3A7plqFBRQQVc0bp5G+t15VQY3nY39S/kBvjPf24wR6T7BCf939AAOxU7tEeRPk3YPeIikf5j8gfek+8GoN0Aaruzs1LqFisFvVs/yDAwF9gRXQ4FanrygqJH2t3PD5MgOjdBAdySie6lfZ9vGxZ7iESeEaL+feG80VZY2g+bTHcS2wiEL/PUToo4yL6/FbSIwAsEJCIQkFKPFw+EKa2b9/S86YFuF3/97HH/7+J0avFGihXr3yZrUopcPgMU=
  file_glob: true
  file:
    - "dist/*"    
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true

  provider: bintray
  file: "bintray.json"
  user: "typekpb"
  key:
    secure: c8GbHQYqh6QgWcSLpYyBOdR0ZLxPwsfWz6WZ2XmxiRcDIU27F9EUxXKkQQ7Gkg+BWryv3+EM9QoUNn4TBZZgwQaAmOK/X29lBLK95NXc6eo06o4tEFDsZmehYgBeBflYgIw5R3XC+l0dZlAJtp3J+NiEodMJSSICchcZ6FRlbt/UBSgRqdue5skpORbUF3isHRSdww92ZDysP47MZKBO/u32AMN1vmChGNE5DQuztB8fltsI0NQfMzsMvbr537KYE2CXActUNQHTgw2ujff769Q7gCLJbdBiA1St3pR7dFt566djTZ+EC1mVb6XxuCYTdnynZ5/S9sZOulHLscSSBIx6V4pMG0WTF/+xliSyrt6+MO9zSgcRYCzrT9qMiHZREEx8u4Xm4phgS2dsQpPOvSQ0wvSVlZNv60r7ZKN5lE555dZbqPQlSodR4+MTD1PJbRFgzn9m3AL9GOjwkGclJ0abEdOyv6ruisSX2QKWDogIIbrnkERrlmtVI/RdWw2oWemfTU92P5ZeJDUA16rYrMh5bnSAYwJLS5GssqJNNkBsTDC5F/nGra9W94Edinl466peY55Jd0vW9s/BAtXzYKXZn008efUxrFxrUXKB7KMBfXsNo8QxD2aGz7oVmxkZZXKZCN/JAGNxeRtlA5OnITmxNu8WnhpoW30J35fQgx0=
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true

  provider: bintray
  file: "bintray_deb.json"
  user: "typekpb"
  key:
    secure: c8GbHQYqh6QgWcSLpYyBOdR0ZLxPwsfWz6WZ2XmxiRcDIU27F9EUxXKkQQ7Gkg+BWryv3+EM9QoUNn4TBZZgwQaAmOK/X29lBLK95NXc6eo06o4tEFDsZmehYgBeBflYgIw5R3XC+l0dZlAJtp3J+NiEodMJSSICchcZ6FRlbt/UBSgRqdue5skpORbUF3isHRSdww92ZDysP47MZKBO/u32AMN1vmChGNE5DQuztB8fltsI0NQfMzsMvbr537KYE2CXActUNQHTgw2ujff769Q7gCLJbdBiA1St3pR7dFt566djTZ+EC1mVb6XxuCYTdnynZ5/S9sZOulHLscSSBIx6V4pMG0WTF/+xliSyrt6+MO9zSgcRYCzrT9qMiHZREEx8u4Xm4phgS2dsQpPOvSQ0wvSVlZNv60r7ZKN5lE555dZbqPQlSodR4+MTD1PJbRFgzn9m3AL9GOjwkGclJ0abEdOyv6ruisSX2QKWDogIIbrnkERrlmtVI/RdWw2oWemfTU92P5ZeJDUA16rYrMh5bnSAYwJLS5GssqJNNkBsTDC5F/nGra9W94Edinl466peY55Jd0vW9s/BAtXzYKXZn008efUxrFxrUXKB7KMBfXsNo8QxD2aGz7oVmxkZZXKZCN/JAGNxeRtlA5OnITmxNu8WnhpoW30J35fQgx0=
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true

  provider: bintray
  file: "bintray_rpm.json"
  user: "typekpb"
  key:
    secure: c8GbHQYqh6QgWcSLpYyBOdR0ZLxPwsfWz6WZ2XmxiRcDIU27F9EUxXKkQQ7Gkg+BWryv3+EM9QoUNn4TBZZgwQaAmOK/X29lBLK95NXc6eo06o4tEFDsZmehYgBeBflYgIw5R3XC+l0dZlAJtp3J+NiEodMJSSICchcZ6FRlbt/UBSgRqdue5skpORbUF3isHRSdww92ZDysP47MZKBO/u32AMN1vmChGNE5DQuztB8fltsI0NQfMzsMvbr537KYE2CXActUNQHTgw2ujff769Q7gCLJbdBiA1St3pR7dFt566djTZ+EC1mVb6XxuCYTdnynZ5/S9sZOulHLscSSBIx6V4pMG0WTF/+xliSyrt6+MO9zSgcRYCzrT9qMiHZREEx8u4Xm4phgS2dsQpPOvSQ0wvSVlZNv60r7ZKN5lE555dZbqPQlSodR4+MTD1PJbRFgzn9m3AL9GOjwkGclJ0abEdOyv6ruisSX2QKWDogIIbrnkERrlmtVI/RdWw2oWemfTU92P5ZeJDUA16rYrMh5bnSAYwJLS5GssqJNNkBsTDC5F/nGra9W94Edinl466peY55Jd0vW9s/BAtXzYKXZn008efUxrFxrUXKB7KMBfXsNo8QxD2aGz7oVmxkZZXKZCN/JAGNxeRtlA5OnITmxNu8WnhpoW30J35fQgx0=
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true

  provider: heroku
  user: butkovic@gmail.com
  api_key:
    - secure: eV1c3ZYp/r8ExVPyXSWYMqFwPf6JW65apZmkU7vLLzvR2cYbC7rXAoCWjTxyjjUs0Nsfq+OGr7eo9Z0ynEeChZCzsdHrPJU8m5LfsQrfbKiKsGptMtgi7twgX9ZSr/NwWumCS0vmVTklLByAUd82OmIhomxRsilcVtZaA9TI3frkYsjMVQ+s5zB4aW2B8xQmFQYcR0SuPvVNsvxG0kZ+5qAg1IgTrQ/PUzMQf3mjWi+F1kyaotMzBRhGJIMXmVyHHBmVOcVTpsCb26xheHwDjJmheGGJbBguqkQgpVvo7/eU0J/HcJ+Klz+yD2tfYs4BJqq3eRIjLDSu+FuwMh5mSf9O7b2wt53bxVzkjro3624dZOL2rKcfoq/Jtxmj6OlGYTWz+bA1CjamSmOEGFV49l5a7LhN6fVQTBORJnXvEzioIH0HL3V1vvg5VYkts4Bfiq94mSDs9CCvoYuY9HkIGz39llL7nXJoMTP8Oq9iV5rfvJHnXh8SDj/NbRvp972uUjC5mUmisHPFFrc9FDec0nJB3dpC3EXyK302SS4CHXxPTNHbRHe4AAzSETKzCl+UFCKgSIQRS1bn2ywSi5vsVW1fYSirVw0g+GU2hnMgBscajyZTt4hX5vIJxwbBpV6hdL4AIGhzwuowxz2CJ9h7ZpkbPC9InEVoOG66yEIP/Nw=
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true