language: go
sudo: false # see: https://docs.travis-ci.com/user/ci-environment/
go:
  - 1.7
script:
  - go generate
  - go test -v ./...
before_deploy: 
  - go get github.com/mitchellh/gox
  - gox
deploy:
  provider: releases
  api_key:
    secure: CmQG72+0QP+NKSMybCAwnR5pY0xYqMPfJgpSNPHW910IIkNsx39pZyGINDUXuwfoHwMkjCdloQpodfkLLjjc+gPhZ7Rt0cMb8NfOUQJeYWUme/yV+KTAk19nMzC/O78xNM1OnwqWCWwPmtH55pvTcqT3R3LjaSlHVveLQsJQa1rYbDxKaGlVPIfezR3HV0DsxRtwNCLOaNoRC3rIT2ILxPeovKhiUG3dbetboO1I1KbcyuDkNqWPLRggNy93NO9VvmkLMVm2Z5CMpkzRv+WLbhedVYfTzM05VOu2UMirh8aSjVSfRMlSHVAxDRXvtGP3hOJlV03LwMeV8zxJo+/nyPna/T7fXTM26w8MKB+uWJlXynHKE/W5t8XUB0BS1KAlum8ZnUhoTZ4YRU6rXAImlT8kJT6ouuVhe5z6ihIVpGjTdT3A7plqFBRQQVc0bp5G+t15VQY3nY39S/kBvjPf24wR6T7BCf939AAOxU7tEeRPk3YPeIikf5j8gfek+8GoN0Aaruzs1LqFisFvVs/yDAwF9gRXQ4FanrygqJH2t3PD5MgOjdBAdySie6lfZ9vGxZ7iESeEaL+feG80VZY2g+bTHcS2wiEL/PUToo4yL6/FbSIwAsEJCIQkFKPFw+EKa2b9/S86YFuF3/97HH/7+J0avFGihXr3yZrUopcPgMU=
  file:
    - "datarator_darwin_386"
    - "datarator_darwin_amd64"
    - "datarator_freebsd_386"
    - "datarator_freebsd_amd64"
    - "datarator_freebsd_arm"
    - "datarator_linux_386"
    - "datarator_linux_amd64"
    - "datarator_linux_arm"
    - "datarator_netbsd_386"
    - "datarator_netbsd_amd64"
    - "datarator_netbsd_arm"
    - "datarator_openbsd_386"
    - "datarator_openbsd_amd64"
    - "datarator_windows_386.exe"
    - "datarator_windows_amd64.exe"
  skip_cleanup: true
  on:
    repo: datarator/datarator
    tags: true